apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: aiplanet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aiplanet
  template:
    metadata:
      labels:
        app: aiplanet
    spec:
      containers:
      - name: aiplanet
        image: ghcr.io/047pegasus/aiplanet:assignment
        ports:
        - containerPort: 8089
  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
